"""
Django settings for OreeStats project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'drf_spectacular',  # Swagger/OpenAPI documentation
    # Local apps
    'email_service',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise for static files (Render)
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "OreeStats.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "OreeStats.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database - Use DATABASE_URL in production (Render), fallback to individual vars for local dev
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }

# Additional AISDR database for external tables (clients, leads)
AISDR_DATABASE_URL = os.getenv('AISDR_DATABASE_URL')
if AISDR_DATABASE_URL:
    DATABASES['aisdr'] = dj_database_url.config(
        default=AISDR_DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
else:
    aisdr_name = os.getenv('AISDR_DB_NAME', os.getenv('DB_NAME'))
    aisdr_user = os.getenv('AISDR_DB_USER', os.getenv('DB_USER'))
    aisdr_password = os.getenv('AISDR_DB_PASSWORD', os.getenv('DB_PASSWORD'))
    aisdr_host = os.getenv('AISDR_DB_HOST', os.getenv('DB_HOST'))
    aisdr_port = os.getenv('AISDR_DB_PORT', os.getenv('DB_PORT'))
    if aisdr_name:
        DATABASES['aisdr'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': aisdr_name,
            'USER': aisdr_user,
            'PASSWORD': aisdr_password,
            'HOST': aisdr_host,
            'PORT': aisdr_port,
        }

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # For future dashboard
        'rest_framework.authentication.SessionAuthentication',  # For admin panel
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Handled by @require_api_key decorator
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings for Swagger/OpenAPI
SPECTACULAR_SETTINGS = {
    'TITLE': 'Oree Stats API',
    'DESCRIPTION': 'Email sending and tracking API for AISDR MVP. Send emails via Gmail API, track opens, clicks, and replies.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'API Support',
        'email': 'support@oreestats.com',
    },
    'LICENSE': {
        'name': 'Proprietary',
    },
    'SERVERS': [
        {
            'url': os.getenv('API_URL', 'http://localhost:8000'),
            'description': 'API Server'
        }
    ] if DEBUG else [
        {
            'url': os.getenv('API_URL', 'https://oreestats-api.onrender.com'),
            'description': 'Production Server'
        }
    ],
    'TAGS': [
        {'name': 'Email', 'description': 'Email sending and status endpoints'},
        {'name': 'Tracking', 'description': 'Email tracking endpoints (opens, clicks, replies)'},
        {'name': 'OAuth', 'description': 'Gmail OAuth2 authentication'},
        {'name': 'Utility', 'description': 'Health check and utility endpoints'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,  # Keep auth after refresh
    },
    'AUTHENTICATION_WHITELIST': [],  # Don't auto-detect DRF auth schemes
    'SECURITY': [
        {
            'ApiKeyAuth': []  # Only show ApiKeyAuth in Swagger
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'API Key',
                'description': 'Enter your API key (without "Bearer" prefix - it will be added automatically)'
            }
        }
    },
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:8000').split(',')]
CORS_ALLOW_CREDENTIALS = True

# Google OAuth2 & Gmail API
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI')
GMAIL_SCOPES = os.getenv('GMAIL_SCOPES', '').split(',')

# Email Tracking
TRACKING_DOMAIN = os.getenv('TRACKING_DOMAIN', 'localhost:8000')
TRACKING_PROTOCOL = os.getenv('TRACKING_PROTOCOL', 'http')

# API Keys
OREE_API_KEY = os.getenv('OREE_API_KEY')

# JWT Settings (for client dashboard authentication)
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')

# Gmail Rate Limiting
GMAIL_RATE_LIMIT_PER_SECOND = float(os.getenv('GMAIL_RATE_LIMIT_PER_SECOND', '2.5'))
GMAIL_DAILY_LIMIT_DEFAULT = int(os.getenv('GMAIL_DAILY_LIMIT_DEFAULT', '2000'))

# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = []

# WhiteNoise configuration for production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
