# Generated by Django 5.2.7 on 2025-11-03 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailClickTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.UUIDField(db_index=True)),
                ("message_id", models.CharField(max_length=255)),
                (
                    "click_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("destination_url", models.TextField()),
                ("click_count", models.IntegerField(default=0)),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_click_tracking",
            },
        ),
        migrations.CreateModel(
            name="EmailTrackingPixel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.UUIDField(db_index=True)),
                ("message_id", models.CharField(max_length=255)),
                (
                    "pixel_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("opened", models.BooleanField(default=False)),
                ("open_count", models.IntegerField(default=0)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_tracking_pixels",
            },
        ),
        migrations.CreateModel(
            name="GmailToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.UUIDField(db_index=True, unique=True)),
                ("email_address", models.EmailField(max_length=254)),
                ("gmail_user_id", models.CharField(blank=True, max_length=255)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_history_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "gmail_tokens",
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.UUIDField(db_index=True)),
                ("client_id", models.UUIDField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("OPEN", "Open"),
                            ("CLICK", "Click"),
                            ("REPLY", "Reply"),
                            ("BOUNCE", "Bounce"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("message_id", models.CharField(db_index=True, max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("sequence_number", models.IntegerField(blank=True, null=True)),
                ("email_subject", models.TextField(blank=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("reply_content", models.TextField(blank=True, null=True)),
                ("reply_snippet", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "email_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead_id", "event_type"],
                        name="email_event_lead_id_28da9b_idx",
                    ),
                    models.Index(
                        fields=["message_id", "created_at"],
                        name="email_event_message_47fd7e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailSendQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.UUIDField(db_index=True)),
                ("client_id", models.UUIDField(db_index=True)),
                ("email_subject", models.TextField()),
                ("email_body", models.TextField()),
                ("email_cta", models.TextField(blank=True)),
                ("sequence_number", models.IntegerField()),
                ("send_delay_days", models.IntegerField(default=0)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_send_queue",
                "ordering": ["scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="email_send__status_a7e6d5_idx",
                    )
                ],
            },
        ),
    ]
