# Generated by Django 5.2.7 on 2025-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsendqueue",
            name="sent_from_email",
            field=models.EmailField(
                blank=True,
                help_text="Which mailbox was used to send this email",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gmailtoken",
            name="daily_send_count",
            field=models.IntegerField(
                default=0, help_text="Emails sent today from this mailbox"
            ),
        ),
        migrations.AddField(
            model_name="gmailtoken",
            name="daily_send_limit",
            field=models.IntegerField(
                default=400, help_text="Gmail daily sending limit per mailbox"
            ),
        ),
        migrations.AddField(
            model_name="gmailtoken",
            name="send_priority",
            field=models.IntegerField(
                default=1, help_text="Priority order for mailbox rotation"
            ),
        ),
        migrations.AlterField(
            model_name="gmailtoken",
            name="client_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="gmailtoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this mailbox was used to send",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="gmailtoken",
            constraint=models.UniqueConstraint(
                fields=("client_id", "email_address"), name="unique_client_email_combo"
            ),
        ),
    ]
