# Generated by Django 5.2.7 on 2025-11-07 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0002_emailsendqueue_sent_from_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsendqueue",
            name="recipient_email",
            field=models.EmailField(
                default="unknown@placeholder.com",
                help_text="Email address to send to (from AISDR database)",
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="LeadMailboxAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lead_id",
                    models.UUIDField(
                        db_index=True, help_text="Lead ID from AISDR database"
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True, help_text="Client ID from AISDR database"
                    ),
                ),
                (
                    "assigned_email",
                    models.EmailField(
                        help_text="Which mailbox is assigned to this lead",
                        max_length=254,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "email_count",
                    models.IntegerField(
                        default=0, help_text="Number of emails sent to this lead"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lead_mailbox_assignments",
                "indexes": [
                    models.Index(
                        fields=["lead_id"], name="lead_mailbo_lead_id_4a40df_idx"
                    ),
                    models.Index(
                        fields=["client_id"], name="lead_mailbo_client__7fd025_idx"
                    ),
                    models.Index(
                        fields=["assigned_email"], name="lead_mailbo_assigne_e146f8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="lead_mailbo_status_f319c1_idx"
                    ),
                ],
                "unique_together": {("lead_id", "client_id")},
            },
        ),
    ]
